### ISSUE TITLE
Can I take over this plugin?

### ISSUE THREAD

**Issue by geheur** [Callum-A/health-notifier#5]
This plugin has a few bugs but I like the idea, I'd like to take it over so that I can fix these issues. Can I do this? (What I need specifically is for you to give permission so that the runelite developers would accept my version of the plugin on their plugin hub. I do not need any access to this repository or anything like that. Just saying "yeah you can do that" on this issue would be sufficient, thanks!)

**Comment by Callum-A** [comment]
Go for it! Yeah I no longer have time but you're more than welcome to take over

**Comment by geheur** [comment]
Thanks for the quick response! I have PR'd it here, if you're interested https://github.com/runelite/plugin-hub/pull/2881. The repo hosting the plugin is now https://github.com/geheur/health-notifier.

Three things you might want to be aware of:
1) LICENSE file - runelite now requires an open-source license file on all hub plugins. For now I have just added myself in the copyright, but if you would like to be added let me know how to credit you.

2) I removed the hitsplat-based health tracking in favor of using NPC#getHealthRatio. This is because it is easier (albeit sometimes slightly less accurate). Please let me know if there were any use-cases you were aware of where that level of accuracy was necessary; if so I can consider adding it back in.

3) I have fixed #1, #3, and #4 in the new version, in case you care to close those. (This issue can also be closed of course, haha).

**Comment by Callum-A** [comment]
> Thanks for the quick response! I have PR'd it here, if you're interested [runelite/plugin-hub#2881](https://github.com/runelite/plugin-hub/pull/2881). The repo hosting the plugin is now https://github.com/geheur/health-notifier.
> 
> Three things you might want to be aware of:
> 
> 1. LICENSE file - runelite now requires an open-source license file on all hub plugins. For now I have just added myself in the copyright, but if you would like to be added let me know how to credit you.
> 2. I removed the hitsplat-based health tracking in favor of using NPC#getHealthRatio. This is because it is easier (albeit sometimes slightly less accurate). Please let me know if there were any use-cases you were aware of where that level of accuracy was necessary; if so I can consider adding it back in.
> 3. I have fixed [Allow the plugin to track more than 1 NPC Name at a time #1](https://github.com/Callum-A/health-notifier/issues/1), [Plugin never notifies for vorkath health <265hp #3](https://github.com/Callum-A/health-notifier/issues/3), and [Plugin breaks when attacking monsters below 100% health at the start of the fight #4](https://github.com/Callum-A/health-notifier/issues/4) in the new version, in case you care to close those. (This issue can also be closed of course, haha).

Thanks mate, doing ace work. For credit you can simply just link my GitHub that'll be sufficient.

Any other design choices its all on you : )

**Comment by geheur** [comment]
to be clear, link your github in the LICENSE file? or in the README?
